# Generated by Django 5.1 on 2024-08-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0004_alter_inmueble_empresa_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='empresa',
        ),
        migrations.AddField(
            model_name='comentario',
            name='Inmueble',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='inmuebleslist_app.inmueble'),
            preserve_default=False,
        ),
    ]
